routes/web.php
<?php

use App\Broadcasting\TelegramChannel;
use App\Demand;
use App\Events\DemandFinished;
use App\Events\WorkspaceCreated;
use App\Notifications\DemandFinishedNotification;
use App\Notifications\WorkspaceNotification;
use App\User;
use App\Workspace;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::view('/', 'index');

Route::group(['prefix' => 'task-manager', 'as' => 'task-manager.', 'middleware' => ['auth']], function () {
    Route::view('/', 'theme.dashboard');
    Route::resource('users', 'UserController');
    Route::resource('roles', 'RoleController');
    Route::resource('permissions', 'PermissionController');
    Route::resource('priorities', 'PriorityController');
    Route::resource('workspaces',  'WorkspaceController');
    Route::resource('workspaces/{workspace}/demands', 'DemandController');
    Route::resource('tasks', 'TaskController')->only('index', 'show');
    Route::get('demands', 'DemandController@mixed')->name('demands.mixed');
    // Route::get('workspaces/{workspace}/tasks/{}', 'TaskController@index');
});

Auth::routes(['register' => false]);


// $user = auth()->user() ?: User::find(2);
// return $user->actions()->with('subject')->limit(5)->get();

// Route::get('/home', 'HomeController@index')->name('home');
// Route::post('/', function(Request $request) {
//     $dt = $request->due_to ? (new Carbon(((int) $request->due_to)))->timezone('Asia/Tehran')->seconds(0) : now();
//     return $dt->format('Y-m-d H:i:s');
// });

// Route::get('/chart', function() {
//     $user = User::first();
//     $dt_from = Carbon::createFromFormat('Y-m-d', '2020-12-21')->setTime(0,0);
//     $dt_to = Carbon::createFromFormat('Y-m-d', '2021-01-20')->setTime(0,0);
//     $craeted_tasks = $user->tasks()
//         ->where('created_at', '<', $dt_to)
//         ->where('created_at', '>=', $dt_from)
//         ->groupBy('date')
//         ->orderBy('date', 'asc')
//         ->get([
//             \DB::raw("COUNT(*) tasks, DATE_FORMAT(created_at, '%Y-%m-%e') date")
//         ]);
//     $finished_tasks = $user->tasks()
//     ->where('finished_at', '<', $dt_to)
//     ->where('finished_at', '>=', $dt_from)
//     ->whereNotNull('finished_at')
//     ->groupBy('date')
//     ->orderBy('date', 'asc')
//     ->get([
//         \DB::raw("COUNT(*) tasks, DATE_FORMAT(finished_at, '%Y-%m-%e') date")
//     ]);
//     $total_count = 0;
//     $finished_count = 0;
//     $target_task_days = collect([]);
//     foreach ($craeted_tasks as $task_day) {
//         $total_count += $task_day->tasks;
//         $task_day->total = $total_count;
//         foreach ($finished_tasks as $finished) {
//             if ($finished->date->diffInSeconds($task_day->date) == 0) {
//                 $finished_count += $finished->tasks;
//                 break;
//             }
//         }
//         $task_day->finished = $finished_count;
//         $task_day->percentage = round($finished_count / $total_count, 2) * 100;
//         $target_task_days->push($task_day);
//     }
//     $task_days = $target_task_days;
//     return view('chart', compact('task_days'));
// });

app/User.php
<?php

namespace App;

use App\Traits\RoleAndPermissionTrait;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Spatie\Activitylog\Traits\CausesActivity;
use Spatie\Activitylog\Traits\LogsActivity;

class User extends Authenticatable
{
    use Notifiable, RoleAndPermissionTrait, SoftDeletes, LogsActivity, CausesActivity;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'first_name', 'last_name', 'avatar_pic', 'telegram_chat_id'
    ];
    protected static $logFillable = true;
    protected static $logName = 'task-manager-activities';
    protected static $logOnlyDirty = true;
    protected static $submitEmptyLogs = false;

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token', 'api_token'
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    protected $appends = ['fullname'];

    public function workspaces()
    {
        return $this->belongsToMany(Workspace::class)->withPivot('is_admin');
    }

    public function tasks()
    {
        return $this->belongsToMany(Task::class);
    }
    public function finished_tasks()
    {
        return $this->tasks()->whereNotNull('finished_at');
    }
    public function unfinished_tasks()
    {
        return $this->tasks()->whereNull('finished_at');
    }
    public function expired_tasks()
    {
        return $this->unfinished_tasks()->whereNotNull('due_to')->where('due_to', '<', now('Asia/Tehran'));
    }
    
    public function demands()
    {
        return $this->hasMany(Demand::class, 'from_id');
    }
    public function asked_demands()
    {
        return $this->hasMany(Demand::class, 'to_id');
    }
    public function getFullnameAttribute()
    {
        return "{$this->first_name}" . ($this->last_name ? " {$this->last_name}" : '');
    }
}

app/Http/Controllers/Api/UserController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\User;
use Illuminate\Http\Request;

class UserController extends Controller
{
    public function index()
    {
        $this->authorize('viewAny', User::class);
        return User::all();
    }
    public function show($user)
    {
        $user = User::with('roles')->findOrFail($user);
        $this->authorize('view', $user);
        return $user;
    }
    public function roles($user)
    {
        return \App\User::findOrFail($user)->roles()->get();
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Role;
use App\User;
use Illuminate\Http\Request;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $this->authorize('viewAny', auth()->user());
        $users = User::with(['roles'])->paginate(15);
        return view('theme.pages.users.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $this->authorize('create', auth()->user());
        return view('theme.pages.users.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->authorize('create', auth()->user());
        $request->validate([
            'name' => 'required|string|min:3|max:60|unique:users,name',
            'email' => 'required|email|min:3|max:60|unique:users,email',
            'first_name' => 'required|string|min:3|max:60',
            'last_name' => 'nullable|string|min:3|max:60',
            'telegram_chat_id' => 'nullable|numeric',
            'avatar_pic' => 'nullable|string',
            'password' => 'required|string|min:8|confirmed',
        ]);
        try {
            \DB::beginTransaction();
            $user = new User();
            $user->name = $request->name;
            $user->first_name = $request->first_name;
            $user->last_name = $request->last_name;
            $user->email = $request->email;
            $user->telegram_chat_id = $request->telegram_chat_id;
            $user->avatar_pic = $request->avatar_pic;
            $user->password = bcrypt($request->password);
            $user->api_token = \Illuminate\Support\Str::uuid();
            $user->save();
            $user->roles()->sync($request->input('roles'));
            \DB::commit();
            return redirect()->to(route('task-manager.users.index'));
        } catch(\Exception $e) {
            \DB::rollBack();
            return back();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $user
     * @return \Illuminate\Http\Response
     */
    public function show($user)
    {
        $user = User::with(['roles', 'workspaces' => function($q) { $q->withCount('users'); }])->findOrFail($user);
        $this->authorize('view', $user);
        return view('theme.pages.users.show', compact('user'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $user
     * @return \Illuminate\Http\Response
     */
    public function edit($user)
    {
        $user = User::findOrFail($user);
        $this->authorize('update', $user);
        return view('theme.pages.users.edit', compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $user)
    {
        $user = User::findOrFail($user);
        $this->authorize('update', $user);
        $request->validate([
            'name' => 'required|string|min:3|max:60|unique:users,name,' . $user->id,
            'email' => 'required|email|min:3|max:60|unique:users,email,' . $user->id,
            'first_name' => 'required|string|min:3|max:60',
            'last_name' => 'nullable|string|min:3|max:60',
            'telegram_chat_id' => 'nullable|numeric',
            'avatar_pic' => 'nullable|string',
            'password' => 'nullable|string|min:8|confirmed',
        ]);
        try {
            \DB::beginTransaction();
            $user->name = $request->name;
            $user->first_name = $request->first_name;
            $user->last_name = $request->last_name;
            $user->email = $request->email;
            if ($request->password) {
                $user->password = bcrypt('password');
            }
            $user->telegram_chat_id = $request->telegram_chat_id;
            if ($request->avatar_pic) {
                $user->avatar_pic = $request->avatar_pic;
            }
            if ($request->password) {
                $user->password = bcrypt($request->password);
            }
            $user->save();
            if (auth()->user()->hasPermission('can_edit_user_role')) {
                $selected = $request->input('roles') ?: [];
                $roles = (in_array('0', $selected)) ? Role::all() : $selected;
                $user->roles()->sync($roles);
            }
            \DB::commit();
            return redirect()->to(route('task-manager.users.edit', ['user' => $user->id]));
        } catch(\Exception $e) {
            \DB::rollBack();
            return back();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $user)
    {
        $user = User::findOrFail($user);
        if ($request->get('force_delete')) {
            $this->authorize('forceDelete', $user);
        } else {
            $this->authorize('delete', $user);
        }
        $user->delete();
    }
}

resources/views/theme/pages/users/create.blade.php
@extends('theme.panel')

@section('title')
افزودن کاربر
@endsection

@section('page-content')
    @component('theme.tools.title', ['title' => 'ایجاد کاربر جدید'])@endcomponent
    <form class="col-12 float-left p-0 form-group text-right" action="{{ route('task-manager.users.store') }}" method="post">
        @csrf
        <div class="col-lg-4 col-md-6 col-12 input-group float-right mb-3">
            <div class="input-group-append">
                <span class="input-group-text"><i class="fas fa-user"></i></span>
            </div>
            <input required type="text" value="{{ old('name') }}" name="name" id="name" class="form-control text-left d-ltr" placeholder="{{ __('username') }}">
        </div>
        <div class="col-lg-4 col-md-6 col-12 input-group float-right mb-3">
            <div class="input-group-append">
                <span class="input-group-text"><i class="fas fa-user"></i></span>
            </div>
            <input required type="text" value="{{ old('first_name') }}" name="first_name" id="first_name" class="form-control" placeholder="{{ __('first_name') }}">
        </div>
        <div class="col-lg-4 col-md-6 col-12 input-group float-right mb-3">
            <div class="input-group-append">
                <span class="input-group-text"><i class="fas fa-user"></i></span>
            </div>
            <input type="text" value="{{ old('last_name') }}" name="last_name" id="last_name" class="form-control" placeholder="{{ __('last_name') }}">
        </div>
        <div class="col-lg-4 col-md-6 col-12 input-group float-right mb-3">
            <div class="input-group-append">
                <span class="input-group-text"><i class="far fa-envelope"></i></span>
            </div>
            <input required type="text" value="{{ old('email') }}" name="email" id="email" class="form-control text-left d-ltr" placeholder="{{ __('email') }}">
        </div>
        <div class="col-lg-4 col-md-6 col-12 input-group float-right mb-3">
            <div class="input-group-append">
                <span class="input-group-text"><i class="fas fa-lock"></i></span>
            </div>
            <input required type="password" name="password" id="password" class="form-control text-left d-ltr" placeholder="{{ __('password') }}">
        </div>
        <div class="col-lg-4 col-md-6 col-12 input-group float-right mb-3">
            <div class="input-group-append">
                <span class="input-group-text"><i class="fas fa-lock"> 2 </i></span>
            </div>
            <input required type="password" name="password_confirmation" id="password_confirmation" class="form-control text-left d-ltr" placeholder="{{ __('confirm') . ' ' . __('password') }}">
        </div>
        <div class="col-lg-4 col-md-6 col-12 input-group float-right mb-3">
            <div class="input-group-append">
                <span class="input-group-text"><i class="fas fa-image"></i></span>
            </div>
            <input type="text" value="{{ old('avatar_pic') }}" name="avatar_pic" id="avatar_pic" class="form-control text-left d-ltr" placeholder="{{ __('avatar_pic') }}">
        </div>
        <div class="col-lg-4 col-md-6 col-12 input-group float-right mb-3">
            <div class="input-group-append">
                <span class="input-group-text"><i class="fas fa-paper-plane"></i></span>
            </div>
            <input type="text" value="{{ old('telegram_chat_id') }}" name="telegram_chat_id" id="telegram_chat_id" class="form-control text-left d-ltr" placeholder="{{ __('telegram_chat_id') }}">
        </div>
        <div class="col-lg-4 col-md-6 col-12 input-group float-right mb-3">
            <div class="input-group-append">
                <span class="input-group-text"><i class="fas fa-user-tag"></i></span>
            </div>
            <select name="roles[]" id="roles" class="form-control text-right" multiple>
                <option></option>
            </select>
        </div>
        <div class="col-12 p-3 float-right text-right">
            <button type="submit" class="btn btn-outline-primary">{{ __('save') }}</button>
        </div>
    </form>
@endsection

@push('scripts')
    <script>
        let perms_route = "{{ route('api.task-manager.roles.index') }}";
        axios.get(perms_route).then(res => {
            let {data} = res;
            data.map(item => {
                $('#roles').append(`<option value="${item.id}">${item.label ? item.label + ' - ' : ''}${item.name}</option>`)
            })
            $('#roles').select2({
                placeholder: "{{ __('roles') }}"
            });
        }) 
    </script>
@endpush

resources/views/theme/pages/users/edit.blade.php
@extends('theme.panel')

@section('title')
ویرایش کاربر ({{ $user->name }})
@endsection

@section('page-content')
    @component('theme.tools.title', ['title' => "ویرایش کاربر {$user->name}"])@endcomponent
    <form class="col-12 float-left p-0 form-group text-right" action="{{ route('task-manager.users.update', ['user' => $user->id]) }}" method="post">
        @csrf
        @method('PUT')
        <div class="col-lg-4 col-md-6 col-12 input-group float-right mb-3">
            <div class="input-group-append">
                <span class="input-group-text"><i class="fas fa-user"></i></span>
            </div>
            <input required type="text" value="{{ old('name') ?: $user->name }}" name="name" id="name" class="form-control text-left d-ltr" placeholder="{{ __('username') }}">
        </div>
        <div class="col-lg-4 col-md-6 col-12 input-group float-right mb-3">
            <div class="input-group-append">
                <span class="input-group-text"><i class="fas fa-user"></i></span>
            </div>
            <input required type="text" value="{{ old('first_name') ?: $user->first_name }}" name="first_name" id="first_name" class="form-control" placeholder="{{ __('first_name') }}">
        </div>
        <div class="col-lg-4 col-md-6 col-12 input-group float-right mb-3">
            <div class="input-group-append">
                <span class="input-group-text"><i class="fas fa-user"></i></span>
            </div>
            <input type="text" value="{{ old('last_name') ?: $user->last_name }}" name="last_name" id="last_name" class="form-control" placeholder="{{ __('last_name') }}">
        </div>
        <div class="col-lg-4 col-md-6 col-12 input-group float-right mb-3">
            <div class="input-group-append">
                <span class="input-group-text"><i class="far fa-envelope"></i></span>
            </div>
            <input required type="text" value="{{ old('email') ?: $user->email }}" name="email" id="email" class="form-control text-left d-ltr" placeholder="{{ __('email') }}">
        </div>
        <div class="col-lg-4 col-md-6 col-12 input-group float-right mb-3">
            <div class="input-group-append">
                <span class="input-group-text"><i class="fas fa-lock"></i></span>
            </div>
            <input type="password" name="password" id="password" class="form-control text-left d-ltr" placeholder="{{ __('password') }}">
        </div>
        <div class="col-lg-4 col-md-6 col-12 input-group float-right mb-3">
            <div class="input-group-append">
                <span class="input-group-text"><i class="fas fa-lock"> 2 </i></span>
            </div>
            <input type="password" name="password_confirmation" id="password_confirmation" class="form-control text-left d-ltr" placeholder="{{ __('confirm') . ' ' . __('password') }}">
        </div>
        @if (auth()->user()->hasRole('developer'))
        <div class="col-lg-4 col-md-6 col-12 input-group float-right mb-3">
            <div class="input-group-append">
                <span class="input-group-text"><i class="fas fa-image"></i></span>
            </div>
            <input type="text" value="{{ old('avatar_pic') ?: $user->avatar_pic }}" name="avatar_pic" id="avatar_pic" class="form-control text-left d-ltr" placeholder="{{ __('avatar_pic') }}">
        </div>
        @endif
        <div class="col-lg-4 col-md-6 col-12 input-group float-right mb-3">
            <div class="input-group-append">
                <span class="input-group-text"><i class="fas fa-paper-plane"></i></span>
            </div>
            <input type="text" value="{{ old('telegram_chat_id') ?: $user->telegram_chat_id }}" name="telegram_chat_id" id="telegram_chat_id" class="form-control text-left d-ltr" placeholder="{{ __('telegram_chat_id') }}">
        </div>
        @if (auth()->user()->hasPermission('can_edit_user_role'))
        <div class="col-lg-4 col-md-6 col-12 input-group float-right mb-3">
            <div class="input-group-append">
                <span class="input-group-text"><i class="fas fa-user-tag"></i></span>
            </div>
            <select name="roles[]" id="roles" class="form-control text-right" multiple>
                <option></option>
            </select>
        </div>
        @endif
        <div class="col-12 p-3 float-right text-right">
            <button type="submit" class="btn btn-outline-primary">{{ __('save') }}</button>
        </div>
    </form>
@endsection

@push('scripts')
@if (auth()->user()->hasPermission('can_edit_user_role'))
    <script>
        let roles_route = "{{ route('api.task-manager.roles.index') }}";
        let roles_of_user_route = "{{ route('api.task-manager.user.roles', ['user' => $user->id]) }}";
        axios.get(roles_route).then(res => {
            let roles = res.data;
            axios.get(roles_of_user_route).then(res => {
                let user_roles = res.data;
                if (roles.length > 0 && user_roles) {
                    roles.map(perm => {
                        let found = !! user_roles.find(item => item.name === perm.name);
                        if (! found) {
                            $('#roles').append(`<option value="${perm.id}">${perm.label ? perm.label + ' - ' : ''}${perm.name}</option>`)
                        } else {
                            $('#roles').append(`<option selected value="${perm.id}">${perm.label ? perm.label + ' - ' : ''}${perm.name}</option>`)
                        }
                    })
                }
                $('#roles').select2({
                    placeholder: "{{ __('roles') }}"
                });
            })
        }) 
    </script>
@endif
@endpush

resources/views/theme/pages/users/index.blade.php
@extends('theme.panel')

@section('title')
لیست کاربران
@endsection

@section('page-content')
    @can('create', \App\User::class)
        @component('theme.tools.title', ['title' => 'لیست کاربران', 'create' => route('task-manager.users.create')]) @endcomponent
    @else
        @component('theme.tools.title', ['title' => 'لیست کاربران']) @endcomponent
    @endcan
    @component('theme.tools.table')
        @component('theme.tools.table-head')
            <th scope="col">#</th>
            <th scope="col">نام خانوادگی</th>
            <th scope="col">نام کاربری</th>
            <th scope="col">ایمیل</th>
            <th scope="col">chat id تلگرام</th>
            <th scope="col">سمت ها</th>
            <th scope="col">ویرایش</th>
            @if (auth()->user()->hasPermission('can_delete_users'))
            <th scope="col">حذف</th>
            @endif
        @endcomponent
        @component('theme.tools.table-body')
            @foreach ($users as $user)
                <tr onclick="getUser({{ $user->id }})">
                    <th scope="row">
                        {{ $loop->index + 1 }}
                    </th>
                    <td class="text-right">
                        <img src="{{ asset($user->avatar_pic ?: 'images/user-avatar.png') }}" alt="" style="height: 30px; widh: 30px;">
                        {{ $user->fullname }}
                    </td>
                    <td>
                        <span class="mr-3">{{ $user->name }}</span>
                    </td>
                    <td>
                        {{ $user->email }}
                    </td>
                    <td>
                        @if ($user->telegram_chat_id)
                            {{ $user->telegram_chat_id }}
                        @else
                            <span class="text-secondary"><em>ندارد</em></span>
                        @endif
                    </td>
                    <td>
                        @if (! $user->roles->count())
                            <span class="text-secondary"><em>ندارد</em></span>
                        @endif
                        @foreach ($user->roles as $role)
                            <a target="_blank" href="{{ route('task-manager.roles.edit', ['role' => $role->id]) }}" class="badge badge-{{ b4_random_color_class() }} p-2">{{ $role->label }}</a>
                        @endforeach
                    </td>
                    <td>
                        @can('update', $user)
                        <a href="{{ route('task-manager.users.edit', ['user' => $user->id]) }}" class="btn btn-sm btn-primary">
                            <i class="fas fa-pencil-alt"></i>
                        </a>
                        @endcan
                    </td>
                    @if (auth()->user()->hasPermission('can_delete_users'))
                    <td>
                        @if (auth()->user()->id !== $user->id)
                            @can('delete', $user)
                            <form action="{{ route('task-manager.users.destroy', ['user' => $user->id]) }}" method="post">
                                @csrf
                                @method('DELETE')
                                <button type="submit" class="btn btn-sm btn-danger delete-btn" deleting-item="user">
                                    <i class="fas fa-trash"></i>
                                </button>
                            </form>
                            @endcan
                        @endif
                    </td>
                    @endif
                </tr>
            @endforeach
        @endcomponent
    @endcomponent
    <div class="col-12 p-0 float-right text-center mt-3 mb-4">
        {{ $users->links() }}
    </div>
@endsection

@push('scripts')
    <script>
        $("table").addClass("table-hover")
        function getUser(userId) {
            window.location.href = USER_ROUTE.replace('userId', userId)
        }
    </script>
    @if (config('app.env') == 'local')
    <script src="{{ asset('js/confirmDelete.js') }}"></script> 
    @else
    <script src="{{ asset(mix('js/confirmDelete.js')) }}"></script>
    @endif
@endpush

resources/views/theme/pages/users/show.blade.php
@extends('theme.panel')

@section('title')
حساب کاربری {{ auth()->user()->id == $user->id ? 'من' : $user->fullname }}
@endsection

@section('page-content')
    <div
        id = "user-profile-react"
        workspaces = "{{ route('api.task-manager.workspaces.index', ['api_token' => auth()->user()->api_token]) }}"
        data-mixed-tasks = "{{ route('api.task-manager.tasks.mixed', ['api_token' => auth()->user()->api_token]) }}"
        data-mixed-demands = "{{ route('api.task-manager.demands.mixed', ['api_token' => auth()->user()->api_token]) }}"
        data-chart-completed="{{ route('api.task-manager.chart.tasks', ['type' => 'completed', 'api_token' => auth()->user()->api_token]) }}"
        data-chart-ontime="{{ route('api.task-manager.chart.tasks', ['type' => 'ontime', 'api_token' => auth()->user()->api_token]) }}"
        data-chart-yearly="{{ route('api.task-manager.chart.tasks', ['type' => 'yearly', 'api_token' => auth()->user()->api_token]) }}"
        task-counter = "{{ route('api.task-manager.counter.tasks', ['api_token' => auth()->user()->api_token]) }}"
        workspace-counter = "{{ route('api.task-manager.counter.workspaces', ['api_token' => auth()->user()->api_token]) }}"
        demand-counter = "{{ route('api.task-manager.counter.demands', ['api_token' => auth()->user()->api_token]) }}"
    ></div>
@endsection

@push('scripts')
    <script>
        const TargetUser = {!! json_encode($user->only(['id', 'fullname', 'avatar_pic', 'name', 'roles'])) !!};
    </script>
    @if (config('app.env') == 'local')
    <script src="{{ asset("js/user-profile.js") }}"></script>
    <script src="{{ asset('js/select2.js') }}"></script>
    <script src="{{ asset('js/chart.js') }}"></script>
    @else
    <script src="{{ asset(mix("js/user-profile.js")) }}"></script>
    <script src="{{ asset(mix('js/select2.js')) }}"></script>
    <script src="{{ asset(mix('js/chart.js')) }}"></script> 
    @endif
    
@endpush