routes/web.php
<?php

use App\Broadcasting\TelegramChannel;
use App\Demand;
use App\Events\DemandFinished;
use App\Events\WorkspaceCreated;
use App\Notifications\DemandFinishedNotification;
use App\Notifications\WorkspaceNotification;
use App\User;
use App\Workspace;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::view('/', 'index');

Route::group(['prefix' => 'task-manager', 'as' => 'task-manager.', 'middleware' => ['auth']], function () {
    Route::view('/', 'theme.dashboard');
    Route::resource('users', 'UserController');
    Route::resource('roles', 'RoleController');
    Route::resource('permissions', 'PermissionController');
    Route::resource('priorities', 'PriorityController');
    Route::resource('workspaces',  'WorkspaceController');
    Route::resource('workspaces/{workspace}/demands', 'DemandController');
    Route::resource('tasks', 'TaskController')->only('index', 'show');
    Route::get('demands', 'DemandController@mixed')->name('demands.mixed');
    // Route::get('workspaces/{workspace}/tasks/{}', 'TaskController@index');
});

Auth::routes(['register' => false]);


// $user = auth()->user() ?: User::find(2);
// return $user->actions()->with('subject')->limit(5)->get();

// Route::get('/home', 'HomeController@index')->name('home');
// Route::post('/', function(Request $request) {
//     $dt = $request->due_to ? (new Carbon(((int) $request->due_to)))->timezone('Asia/Tehran')->seconds(0) : now();
//     return $dt->format('Y-m-d H:i:s');
// });

// Route::get('/chart', function() {
//     $user = User::first();
//     $dt_from = Carbon::createFromFormat('Y-m-d', '2020-12-21')->setTime(0,0);
//     $dt_to = Carbon::createFromFormat('Y-m-d', '2021-01-20')->setTime(0,0);
//     $craeted_tasks = $user->tasks()
//         ->where('created_at', '<', $dt_to)
//         ->where('created_at', '>=', $dt_from)
//         ->groupBy('date')
//         ->orderBy('date', 'asc')
//         ->get([
//             \DB::raw("COUNT(*) tasks, DATE_FORMAT(created_at, '%Y-%m-%e') date")
//         ]);
//     $finished_tasks = $user->tasks()
//     ->where('finished_at', '<', $dt_to)
//     ->where('finished_at', '>=', $dt_from)
//     ->whereNotNull('finished_at')
//     ->groupBy('date')
//     ->orderBy('date', 'asc')
//     ->get([
//         \DB::raw("COUNT(*) tasks, DATE_FORMAT(finished_at, '%Y-%m-%e') date")
//     ]);
//     $total_count = 0;
//     $finished_count = 0;
//     $target_task_days = collect([]);
//     foreach ($craeted_tasks as $task_day) {
//         $total_count += $task_day->tasks;
//         $task_day->total = $total_count;
//         foreach ($finished_tasks as $finished) {
//             if ($finished->date->diffInSeconds($task_day->date) == 0) {
//                 $finished_count += $finished->tasks;
//                 break;
//             }
//         }
//         $task_day->finished = $finished_count;
//         $task_day->percentage = round($finished_count / $total_count, 2) * 100;
//         $target_task_days->push($task_day);
//     }
//     $task_days = $target_task_days;
//     return view('chart', compact('task_days'));
// });

app/Workspace.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Workspace extends Model
{
    use SoftDeletes;
    public function users()
    {
        return $this->belongsToMany(User::class)->withPivot('is_admin');
    }
    public function admins()
    {
        return $this->users()->wherePivot('is_admin', true)->withPivotValue('is_admin', true);
    }
    public function members()
    {
        return $this->users()->wherePivot('is_admin', false)->withPivotValue('is_admin', false);
    }
    
    public function tasks()
    {
        return $this->hasMany(Task::class);
    }
    public function finished_tasks()
    {
        return $this->tasks()->whereNotNull('finished_at');
    }
    public function unfinished_tasks()
    {
        return $this->tasks()->whereNull('finished_at');
    }
    public function expired_tasks()
    {
        return $this->unfinished_tasks()->whereNotNull('due_to')->where('due_to', '<', now('Asia/Tehran'));
    }
    
    public function demands()
    {
        return $this->hasMany(Demand::class);
    }
    public function demands_left()
    {
        return $this->hasMany(Demand::class)->whereNull('finished_at');
    }
}

app/Http/Controllers/Api/WorkspaceController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Workspace;
use Illuminate\Http\Request;

class WorkspaceController extends Controller
{
    public function index(Request $request)
    {
        $user = ($request->user_id) ? \App\User::find($request->user_id) : $request->user();
        return $user->workspaces()->with('users')->withCount(['tasks', 'finished_tasks', 'demands_left'])->get();
    }
    public function show(Request $request, Workspace $workspace)
    {
        $this->authorize('view', $workspace);
        return $workspace->load('users');
    }
    public function groups(Request $request, $workspace)
    {
        $groups = $request->user()->tasks()->whereWorkspaceId($workspace)
        ->select('group as name', \DB::raw('count(*) as tasks'))
        ->groupBy('group')->get();
        return $groups;
    }
}

app/Http/Controllers/WorkspaceController.php
<?php

namespace App\Http\Controllers;

use App\Events\WorkspaceCreated;
use App\User;
use App\Workspace;
use Illuminate\Http\Request;
use Illuminate\Validation\Rule;

class WorkspaceController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (\Gate::allows('viewAny', Workspace::class)) {
            $workspaces = Workspace::withCount(['tasks', 'finished_tasks', 'demands_left'])->with('users')->paginate(5);
        } else {
            $workspaces = auth()->user()->workspaces()->withCount(['tasks', 'finished_tasks', 'demands_left'])->with('users')->paginate(5);
        }
        return view('theme.pages.workspaces.index', compact('workspaces'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $this->authorize('create', Workspace::class);
        $users = User::where('id', '!=', auth()->user()->id)->get();
        return view('theme.pages.workspaces.create', compact('users'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->authorize('create', Workspace::class);
        $request->validate([
            'title' => [
                'required',
                'min:3',
                'max:60',
                Rule::unique('workspaces', 'title')->whereNull('deleted_at')
            ],
            'description' => 'required|string',
            'avatar_pic' => 'nullable|string'
        ]);  
        $workspace = new Workspace();
        $workspace->title = $request->title;
        $workspace->description = $request->description;
        $workspace->avatar_pic = $request->avatar_pic;
        $workspace->save();
        $workspace->admins()->attach([auth()->user()->id]);
        $workspace->members()->attach($request->input('members'));
        dispatch(function () use($workspace) {
            event(new WorkspaceCreated($workspace));
        })->afterResponse();
        flash()->success("پروژه {$workspace->title} با موفقیت ساخته شده");
        return response()->redirectTo(route('task-manager.workspaces.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $workspace
     * @return \Illuminate\Http\Response
     */
    public function show($workspace)
    {
        $workspace = Workspace::with([
            'users' => function($q) use($workspace) {
                $q->withCount([
                    'tasks'   => function($q) use($workspace) {$q->where('workspace_id', $workspace);},
                    'demands' => function($q) use($workspace) {$q->where('workspace_id', $workspace);},
                    'asked_demands' => function($q) use($workspace) {$q->where('workspace_id', $workspace);}
                ])->with('roles');
            }
        ])->withCount(['tasks', 'demands', 'finished_tasks', 'demands_left'])->findOrFail($workspace);
        $this->authorize('view', $workspace);
        return view('theme.pages.workspaces.show', compact('workspace'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $workspace
     * @return \Illuminate\Http\Response
     */
    public function edit($workspace)
    {
        $workspace = Workspace::with(['admins', 'members'])->findOrFail($workspace);
        $this->authorize('update', $workspace);
        $users = User::where('id', '!=', auth()->user()->id)->get();
        return view('theme.pages.workspaces.edit', compact('workspace', 'users'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $workspace
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $workspace)
    {
        $workspace = Workspace::findOrFail($workspace);
        $this->authorize('update', $workspace);
        $request->validate([
            'title' => [
                'required',
                'min:3',
                'max:60',
                Rule::unique('workspaces', 'title')->ignore($workspace->id)->whereNull('deleted_at')
            ],
            'description' => 'required|string',
            'avatar_pic' => 'nullable|string'
        ]); 
        $workspace->title = $request->title;
        $workspace->description = $request->description;
        $workspace->avatar_pic = $request->avatar_pic;
        $members = $request->input('members') ?: [];
        $members = collect($members)->diff($request->input('admins'));
        $workspace->save();
        $admins = $request->input('admins') ? array_merge([auth()->user()->id], $request->input('admins')) : [auth()->user()->id];
        $workspace->admins()->sync($admins);
        $workspace->members()->sync($members);
        flash()->success("پروژه {$workspace->title} با موفقیت بروزرسانی شده");
        return redirect()->to(route('task-manager.workspaces.edit', ['workspace' => $workspace->id]));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $workspace
     * @return \Illuminate\Http\Response
     */
    public function destroy(Workspace $workspace)
    {
        $this->authorize('delete', $workspace);
        $workspace->delete();
        return redirect()->to(route('task-manager.workspaces.index'));
    }
}

resources/views/theme/pages/workspaces/create.blade.php
@extends('theme.panel')

@section('title')
افزودن پروژه
@endsection

@section('page-content')
    @component('theme.tools.title', ['title' => 'ایجاد پروژه جدید'])@endcomponent
    <form class="col-12 float-left p-0 form-group text-right" action="{{ route('task-manager.workspaces.store') }}" method="post">
        @csrf
        <div class="col-lg-4 col-md-6 col-12 input-group float-right mb-3">
            <div class="input-group-append">
                <span class="input-group-text"><i class="fas fa-user"></i></span>
            </div>
            <input required type="text" value="{{ old('title') }}" name="title" id="title" class="form-control" placeholder="{{ __('title') }}">
        </div>
        <div class="col-lg-4 col-md-6 col-12 input-group float-right mb-3">
            <div class="input-group-append">
                <span class="input-group-text"><i class="fas fa-image"></i></span>
            </div>
            <input type="text" value="{{ old('avatar_pic') }}" name="avatar_pic" id="avatar_pic" class="form-control text-left d-ltr" placeholder="{{ __('avatar_pic') }}">
        </div>
        <br><br><br>
        <div class="col-lg-4 col-md-6 col-12 input-group float-right mb-3 ">
            <div class="input-group-append">
                <span class="input-group-text"><i class="fas fa-user-tag"></i></span>
            </div>
            <select name="members[]" id="members" class="form-control text-right" multiple>
                <option></option>
                @foreach ($users as $user)
                    <option value="{{ $user->id }}">{{ $user->fullname }}</option>
                @endforeach
            </select>
        </div>
        <br><br><br>
        <div class="col-md-6 offset-md-6 col-12 input-group float-right mb-3">
            <textarea required rows="10" name="description" id="description" class="form-control" placeholder="{{ __('description') }}">{{ old('description') }}</textarea>
        </div>
        <div class="col-12 p-3 float-right text-right">
            <button type="submit" class="btn btn-outline-primary">{{ __('save') }}</button>
        </div>
    </form>
@endsection

@push('scripts')
    <script>
        $('#members').select2({
            placeholder: "{{ __('employees') }}"
        });
    </script>
@endpush

resources/views/theme/pages/workspaces/edit.blade.php
@extends('theme.panel')

@section('title')
ویرایش پروژه ({{ $workspace->title }})
@endsection

@section('page-content')
    @component('theme.tools.title', ['title' => "ویرایش پروژه {$workspace->title}"])@endcomponent
    <form class="col-12 float-left p-0 form-group text-right" action="{{ route('task-manager.workspaces.update', ['workspace' => $workspace->id]) }}" method="post">
        @csrf
        @method('PUT')
        <div class="col-lg-4 col-md-6 col-12 input-group float-right mb-3">
            <div class="input-group-append">
                <span class="input-group-text"><i class="fas fa-user"></i></span>
            </div>
            <input required type="text" value="{{ old('title') ?: $workspace->title }}" name="title" id="title" class="form-control" placeholder="{{ __('title') }}">
        </div>
        <div class="col-lg-4 col-md-6 col-12 input-group float-right mb-3">
            <div class="input-group-append">
                <span class="input-group-text"><i class="fas fa-image"></i></span>
            </div>
            <input type="text" value="{{ old('avatar_pic') ?: $workspace->avatar_pic }}" name="avatar_pic" id="avatar_pic" class="form-control text-left d-ltr" placeholder="{{ __('avatar_pic') }}">
        </div>
        <br><br><br><hr class="d-none d-md-block border-top">
        <div class="col-lg-4 col-md-6 col-12 input-group float-right mb-3">
            <div class="input-group-append">
                <span class="input-group-text"><i class="fas fa-user-tag"></i></span>
            </div>
            <select name="admins[]" id="admins" class="form-control text-right" multiple>
                <option></option>
                @foreach ($users as $user)
                    <option 
                    @foreach ($workspace->admins as $admin)
                        @if ($admin->id === $user->id)
                            selected
                        @endif
                    @endforeach
                    value="{{ $user->id }}">{{ $user->fullname }}</option>
                @endforeach
            </select>
        </div>
        <div class="col-lg-4 col-md-6 col-12 input-group float-right mb-3">
            <div class="input-group-append">
                <span class="input-group-text"><i class="fas fa-user-tag"></i></span>
            </div>
            <select name="members[]" id="members" class="form-control text-right" multiple>
                <option></option>
                @foreach ($users as $user)
                    <option
                    @foreach ($workspace->members as $member)
                        @if ($member->id === $user->id)
                            selected
                        @endif
                    @endforeach
                    value="{{ $user->id }}">{{ $user->fullname }}</option>
                @endforeach
            </select>
        </div>
        {{-- <br><br><br><hr> --}}
        <div class="col-12 input-group float-right mt-md-4 pt-md-3 border-top">
            <textarea required rows="10" name="description" id="description" class="form-control col-lg-6 col-md-6 offset-md-6 col-12" placeholder="{{ __('description') }}">{{ old('description') ?: $workspace->description }}</textarea>
        </div>
        <div class="col-12 p-3 float-right text-right">
            <button type="submit" class="btn btn-outline-primary">{{ __('save') }}</button>
        </div>
    </form>
@endsection

@push('scripts')
    <script>
        $('#admins').select2({
            placeholder: "{{ __('admins') }}"
        });
        $('#members').select2({
            placeholder: "{{ __('employees') }}"
        });
    </script>
@endpush

resources/views/theme/pages/workspaces/index.blade.php
@extends('theme.panel')

@section('title')
لیست پروژه ها
@endsection

@section('page-content')
    @can('create', \App\Workspace::class)
    @component('theme.tools.title', ['title' => 'لیست پروژه ها', 'create' => route('task-manager.workspaces.create')]) @endcomponent
    @else
        @component('theme.tools.title', ['title' => 'لیست پروژه ها']) @endcomponent
    @endcan
    
    @component('theme.tools.table')
        @component('theme.tools.table-head')
            <th scope="col">#</th>
            <th scope="col">عنوان پروژه</th>
            <th scope="col">کارمندان</th>
            <th scope="col">وضعیت وظایف</th>
            <th scope="col">نیاز های جاری</th>
            @if (auth()->user()->hasPermission('can_update_workspaces'))
            <th scope="col">ویرایش</th>
            @endif
            @if (auth()->user()->hasPermission('can_delete_workspaces'))
            <th scope="col">حذف</th>
            @endif
        @endcomponent
        @component('theme.tools.table-body')
            @foreach ($workspaces as $workspace)
                <tr>
                    <th scope="row">
                        {{ $loop->index + 1 }}
                    </th>
                    <td class="text-right">
                        <img src="{{ asset($workspace->avatar_pic ?: 'images/idea.svg') }}" alt="" style="height: 30px; widh: 30px;">
                        <a href="{{ route('task-manager.workspaces.show', ['workspace' => $workspace->id]) }}">{{ $workspace->title }}</a>
                    </td>
                    <td>
                        <div class="employees-container horizontal-centerlize">
                            @if (count($workspace->users) > 1)
                                <span>{{ count($workspace->users) }} <i class="fas fa-users"></i></span>
                            @elseif(count($workspace->users))
                                <span><i class="fas fa-user"></i></span>
                            @else
                                <i class="fas fa-user-slash"></i>
                            @endif
                            <div class="dropdown-users d-none">
                                @foreach ($workspace->users as $user)
                                    <div class="user-dropdown-item animated jackInTheBox">
                                        <div class="user-right-flex">
                                            <div class="user-img-container ml-2">
                                                <img src="{{ asset($user->avatar_pic ?: 'images/user-avatar.png') }}" />
                                            </div>
                                            <div class="user-info ml-2">
                                                <p>{{ $user->fullname }}</p>
                                                <a href="{{ route('task-manager.users.show', ['user' => $user->id]) }}">{{"@".$user->name }}</a>
                                            </div>
                                        </div>
                                        <div class="user-label-container">
                                            @if ($user->pivot->is_admin == 1)
                                                <button class="btn btn-sm btn-success rtl admin"><span>ادمین<i class="fas fa-user-tie mr-1"></i></span></button>
                                            @else
                                                <button class="btn btn-sm btn-primary rtl"><span>عضو<i class="fas fa-user mr-1"></i></span></button>
                                            @endif 
                                        </div>
                                    </div>
                                @endforeach
                            </div>
                        </div>
                    </td>
                    <td class="no-break">
                        کل : <span class="badge badge-primary ml-md-4 d-block d-md-inline mb-1 mb-md-0">{{ $workspace->tasks_count }}</span>
                        اتمام : <span class="badge badge-success ml-md-4 d-block d-md-inline mb-1 mb-md-0">{{ $workspace->finished_tasks_count }}</span>
                        باقی مانده : <span class="badge badge-danger ml-md-4 d-block d-md-inline mb-1 mb-md-0">{{ $workspace->tasks_count - $workspace->finished_tasks_count }}</span>
                    </td>
                    <td>
                        {{ $workspace->demands_left_count }}
                    </td>
                    @if (auth()->user()->hasPermission('can_update_workspaces'))
                    <td>
                        @can('update', $workspace)
                        <a href="{{ route('task-manager.workspaces.edit', ['workspace' => $workspace->id]) }}" class="btn btn-sm btn-primary">
                            <i class="fas fa-pencil-alt"></i>
                        </a>
                        @endcan
                    </td>
                    @endif
                    @if (auth()->user()->hasPermission('can_delete_workspaces'))
                    <td>
                        @can('delete', $workspace)
                        <form action="{{ route('task-manager.workspaces.destroy', ['workspace' => $workspace->id]) }}" method="post">
                            @csrf
                            @method('DELETE')
                            <button type="submit" class="btn btn-sm btn-danger delete-btn" deleting-item="workspace">
                                <i class="fas fa-trash"></i>
                            </button>
                        </form>
                        @endcan
                    </td>
                    @endif
                </tr>
            @endforeach
        @endcomponent
    @endcomponent
    <div class="col-12 p-0 float-right text-center mt-3 mb-4">
        {{ $workspaces->links() }}
    </div>
@endsection

@push('scripts')
    @if (config('app.env') == 'local')
    <script src="{{ asset('js/confirmDelete.js') }}"></script> 
    @else
    <script src="{{ asset(mix('js/confirmDelete.js')) }}"></script>
    @endif
@endpush

resources/views/theme/pages/workspaces/show.blade.php
@extends('theme.panel')

@section('title')
پروژه ({{ $workspace->title }})
@endsection

@section('page-content')
    <div class="col-md-10 offset-md-1 col-12 pr-0 pl-0">
        <div class="col-12 float-right mb-3 pr-0 pl-0 pr-md-3 pl-md-3 animated flipInY">
            <img class="float-right" src="{{ asset($workspace->avatar_pic ?: "images/idea.svg") }}" style="height: 50px; widht: 50px;" alt="">
            <h4 class="text-right mt-3">
                {{ $workspace->title }}
            </h4>
        </div>
        <div class="workspace-sub-info float-right col-12">
            <a id="tasks-quick-scroll" class="rtl" href="#tasks">
                <span><i class="fas fa-tasks ml-1 animated heartBeat delay-2s"></i><span class="number ml-1">{{ $workspace->tasks_count }}</span>مسئولیت</span>
            </a>
            <span><i class="fas fa-thumbtack ml-1 animated heartBeat delay-2s"></i><span class="number ml-1">{{ $workspace->tasks_count - $workspace->finished_tasks_count }}</span>مسئولیت جاری</span>
            <span><i class="far fa-check-square ml-1 animated heartBeat delay-2s"></i><span class="number ml-1">{{ $workspace->finished_tasks_count }}</span>مسئولیت انجام شده</span>
            <a class="rtl" href="{{ route('task-manager.demands.index', ['workspace' => $workspace->id]) }}">
                <span><i class="fas fa-clipboard-list ml-1 animated heartBeat delay-2s"></i><span class="number ml-1">{{ $workspace->demands_count }}</span><b>خواسته</b></span>
            </a>
            <span><i class="far fa-comments ml-1 animated heartBeat delay-2s"></i><span class="number ml-1">{{ $workspace->demands_left_count }}</span>خواسته جاری</span>
            <span><i class="far fa-check-circle ml-1 animated heartBeat delay-2s"></i><span class="number ml-1">{{ $workspace->demands_count -  $workspace->demands_left_count }}</span>خواسته انجام شده</span>
        </div>
        <div class="animated flipInX">
            <div class="title-section workspace-title-section col-12">
                <i class="fas fa-user-secret"></i>
                <h4 class="">اعضا ({{ count($workspace->users) }}):</h4>      
            </div>    
            <div>
            @component('theme.tools.table', ['class' => 'table-sm'])
                @component('theme.tools.table-head')
                    <th scope="col">#</th>
                    <th scope="col">نام</th>
                    <th scope="col">وضعیت</th>
                    <th scope="col">سمت سازمانی</th>
                @endcomponent
                @component('theme.tools.table-body')
                    @foreach ($workspace->users as $user)
                        <tr>
                            <th scope="row">
                                {{ $loop->index + 1 }}
                            </th>
                            <td>
                                <div class="name-col-user-workspace text-right">
                                    <div class="user-info-workspace ml-2">
                                        <img src="{{ asset($user->avatar_pic ?: 'images/user-avatar.png') }}" alt="">
                                        <a class="mr-2" href="{{ route('task-manager.users.show', ['user' => $user->id]) }}">{{ $user->fullname }}</a>
                                    </div>
                                    @if ($user->pivot->is_admin)
                                        <span class="badge badge-dark">ادمین</span>
                                    @endif
                                </div>
                            </td>
                            <td class="no-break">
                                مسئولیت : <span class="badge badge-warning ml-md-4 d-block d-md-inline mb-1 mb-md-0">{{ $user->tasks_count }} <i class="fas fa-briefcase"></i></span>
                                درخواست : <span class="badge badge-primary ml-md-4 d-block d-md-inline mb-1 mb-md-0">{{ $user->asked_demands_count }} <i class="fas fa-arrow-down"></i></span>
                                نیاز : <span class="badge badge-danger ml-md-4 d-block d-md-inline mb-1 mb-md-0">{{ $user->demands_count }} <i class="fas fa-arrow-up"></i></span>
                            </td>
                            <td>
                                @foreach ($user->roles as $role)
                                    @if (! $loop->last)
                                        {{ $role->label }}،
                                    @else
                                        {{ $role->label }}
                                    @endif
                                @endforeach
                            </td>
                        </tr>
                    @endforeach
                @endcomponent
            @endcomponent
            </div>
        </div>
        <div
            id="workspace-react"
            list_tasks_api = "{{ route('api.task-manager.tasks.index', ['workspace' => $workspace->id, 'api_token' => auth()->user()->api_token]) }}"
            add_task_api = "{{ route('api.task-manager.tasks.store', ['workspace' => $workspace->id, 'api_token' => auth()->user()->api_token]) }}"
            task_route = "{{ route('task-manager.tasks.show', ['task' => 'taskId']) }}"
            workspace_api = "{{ route('api.task-manager.workspaces.show', ['workspace' => $workspace->id, 'api_token' => auth()->user()->api_token]) }}"
            get-all-users="{{ route('api.task-manager.users.index', ['api_token' => auth()->user()->api_token]) }}"
            toggle-task-state-api = "{{ route('api.task-manager.tasks.toggle_state', ['workspace' => $workspace->id, 'task' => 'taskId', 'api_token' => auth()->user()->api_token]) }}"
        ></div>
    </div>
@endsection

@push('scripts')
    <script>
        const CAN_VIEW_AS_ADMIN = {{ \Gate::allows('update', $workspace) ? 'true' : 'false' }};
        var VIEW_AS_ADMIN       = {{ request()->view_as_admin == 'true' ? 'true' : 'false' }}; 
        var simple_search_url = "{{ route('api.task-manager.tasks.search.simple', ['api_token' => auth()->user()->api_token]) }}"
        $("#tasks-quick-scroll").on("click", function() {
            $(".contentbar").animate({
                scrollTop: $("#filter-box").offset().top
            }, 1000);
        })
    </script>
    @if (config('app.env') == 'local')
    <script src="{{ asset('js/datepicker.js') }}"></script>
    <script src="{{ asset('js/workspace.js') }}"></script>
    <script src="{{ asset('js/select2.js') }}"></script>
    @else
    <script src="{{ asset(mix('js/datepicker.js')) }}"></script>
    <script src="{{ asset(mix('js/workspace.js')) }}"></script>
    <script src="{{ asset(mix('js/select2.js')) }}"></script>   
    @endif
@endpush