routes/web.php
<?php

use App\Broadcasting\TelegramChannel;
use App\Demand;
use App\Events\DemandFinished;
use App\Events\WorkspaceCreated;
use App\Notifications\DemandFinishedNotification;
use App\Notifications\WorkspaceNotification;
use App\User;
use App\Workspace;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::view('/', 'index');

Route::group(['prefix' => 'task-manager', 'as' => 'task-manager.', 'middleware' => ['auth']], function () {
    Route::view('/', 'theme.dashboard');
    Route::resource('users', 'UserController');
    Route::resource('roles', 'RoleController');
    Route::resource('permissions', 'PermissionController');
    Route::resource('priorities', 'PriorityController');
    Route::resource('workspaces',  'WorkspaceController');
    Route::resource('workspaces/{workspace}/demands', 'DemandController');
    Route::resource('tasks', 'TaskController')->only('index', 'show');
    Route::get('demands', 'DemandController@mixed')->name('demands.mixed');
    // Route::get('workspaces/{workspace}/tasks/{}', 'TaskController@index');
});

Auth::routes(['register' => false]);


// $user = auth()->user() ?: User::find(2);
// return $user->actions()->with('subject')->limit(5)->get();

// Route::get('/home', 'HomeController@index')->name('home');
// Route::post('/', function(Request $request) {
//     $dt = $request->due_to ? (new Carbon(((int) $request->due_to)))->timezone('Asia/Tehran')->seconds(0) : now();
//     return $dt->format('Y-m-d H:i:s');
// });

// Route::get('/chart', function() {
//     $user = User::first();
//     $dt_from = Carbon::createFromFormat('Y-m-d', '2020-12-21')->setTime(0,0);
//     $dt_to = Carbon::createFromFormat('Y-m-d', '2021-01-20')->setTime(0,0);
//     $craeted_tasks = $user->tasks()
//         ->where('created_at', '<', $dt_to)
//         ->where('created_at', '>=', $dt_from)
//         ->groupBy('date')
//         ->orderBy('date', 'asc')
//         ->get([
//             \DB::raw("COUNT(*) tasks, DATE_FORMAT(created_at, '%Y-%m-%e') date")
//         ]);
//     $finished_tasks = $user->tasks()
//     ->where('finished_at', '<', $dt_to)
//     ->where('finished_at', '>=', $dt_from)
//     ->whereNotNull('finished_at')
//     ->groupBy('date')
//     ->orderBy('date', 'asc')
//     ->get([
//         \DB::raw("COUNT(*) tasks, DATE_FORMAT(finished_at, '%Y-%m-%e') date")
//     ]);
//     $total_count = 0;
//     $finished_count = 0;
//     $target_task_days = collect([]);
//     foreach ($craeted_tasks as $task_day) {
//         $total_count += $task_day->tasks;
//         $task_day->total = $total_count;
//         foreach ($finished_tasks as $finished) {
//             if ($finished->date->diffInSeconds($task_day->date) == 0) {
//                 $finished_count += $finished->tasks;
//                 break;
//             }
//         }
//         $task_day->finished = $finished_count;
//         $task_day->percentage = round($finished_count / $total_count, 2) * 100;
//         $target_task_days->push($task_day);
//     }
//     $task_days = $target_task_days;
//     return view('chart', compact('task_days'));
// });

app/Permission.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Permission extends Model
{
    public $timestamps = false;
    public function roles()
    {
        return $this->belongsToMany(Role::class);
    }
}

app/Http/Controllers/PermissionController.php
<?php

namespace App\Http\Controllers;

use App\Permission;
use Illuminate\Http\Request;

class PermissionController extends Controller
{
    public $route_prefix = parent::TASKROUTE . "permissions";
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $permissions = Permission::withCount(['roles'])->paginate(15);
        return view('theme.pages.permissions.index', compact('permissions'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('theme.pages.permissions.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $permission = new Permission();
        $permission->key = $request->key;
        $permission->label = $request->label;
        $permission->save();
        return redirect()->to(route("{$this->route_prefix}.index"));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $permission
     * @return \Illuminate\Http\Response
     */
    public function show($permission)
    {
        $permission = Permission::with('roles.users')->findOrFail($permission);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $permission
     * @return \Illuminate\Http\Response
     */
    public function edit($permission)
    {
        $permission = Permission::findOrFail($permission);
        return view('theme.pages.permissions.edit', compact('permission'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $permission
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $permission)
    {
        $permission = Permission::findOrFail($permission);
        $permission->key = $request->key; // unique
        $permission->label = $request->label;
        $permission->save();
        return redirect()->to(route("{$this->route_prefix}.edit", ['permission' => $permission->id]));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $permission
     * @return \Illuminate\Http\Response
     */
    public function destroy($permission)
    {
        Permission::findOrFail($permission)->delete();
        return back();
    }
}

resources/views/theme/pages/permissions/create.blade.php
@extends('theme.panel')

@section('title')
افزودن مجوز
@endsection

@section('page-content')
    @component('theme.tools.title', ['title' => 'ایجاد مجوز جدید'])@endcomponent
    <form class="col-12 float-left p-0 form-group text-right" action="{{ route('task-manager.permissions.store') }}" method="post">
        @csrf
        <div class="col-lg-4 col-md-6 col-12 input-group float-right">
            <div class="input-group-append">
                <span class="input-group-text"><i class="fas fa-tag"></i></span>
            </div>
            <input type="text" value="{{ old('label') }}" name="label" id="label" class="form-control" placeholder="{{ __('label') }}">
        </div>
        <div class="col-lg-4 col-md-6 col-12 input-group float-right">
            <div class="input-group-append">
                <span class="input-group-text"><i class="fas fa-key"></i></span>
            </div>
            <input type="text" value="{{ old('key') }}" name="key" id="key" class="form-control" placeholder="{{ __('key') }}">
        </div>
        <div class="col-12 p-3 float-right text-right">
            <button type="submit" class="btn btn-outline-primary">{{ __('save') }}</button>
        </div>
    </form>
@endsection

resources/views/theme/pages/permissions/edit.blade.php
@extends('theme.panel')

@section('title')
ویرایش مجوز ({{ $permission->key }})
@endsection

@section('page-content')
    @component('theme.tools.title', ['title' => "ویرایش مجوز شماره #{$permission->id}"])@endcomponent
    <form class="col-12 float-left p-0 form-group text-right" action="{{ route('task-manager.permissions.update', ['permission' => $permission->id]) }}" method="post">
        @csrf
        @method('PUT')
        <div class="col-lg-4 col-md-6 col-12 input-group float-right">
            <div class="input-group-append">
                <span class="input-group-text"><i class="fas fa-tag"></i></span>
            </div>
            <input type="text" value="{{ old('label') ?: $permission->label }}" name="label" id="label" class="form-control" placeholder="{{ __('label') }}">
        </div>
        <div class="col-lg-4 col-md-6 col-12 input-group float-right">
            <div class="input-group-append">
                <span class="input-group-text"><i class="fas fa-key"></i></span>
            </div>
            <input type="text" value="{{ old('key')   ?: $permission->key }}" name="key" id="key" class="form-control" placeholder="{{ __('key') }}">
        </div>
        <div class="col-12 p-3 float-right text-right">
            <button type="submit" class="btn btn-outline-primary">{{ __('save') }}</button>
        </div>
    </form>
@endsection

resources/views/theme/pages/permissions/index.blade.php
@extends('theme.panel')

@section('title')
لیست مجوز ها
@endsection

@section('page-content')
    @component('theme.tools.title', ['title' => 'لیست مجوز ها', 'create' => route('task-manager.permissions.create')])
        
    @endcomponent
    @component('theme.tools.table')
        @component('theme.tools.table-head')
            <th scope="col">#</th>
            <th scope="col">کلید</th>
            <th scope="col">برچسب</th>
            <th scope="col">ویرایش</th>
            <th scope="col">حذف</th>
        @endcomponent
        @component('theme.tools.table-body')
            @foreach ($permissions as $permission)
                <tr>
                    <th scope="row">
                        {{ $loop->index + 1 }}
                    </th>
                    <td>
                        <span aria-disabled="true" class="btn btn-sm btn-outline-dark">
                            {{ $permission->key }}
                            <span class="badge badge-secondary mr-2">{{ $permission->roles_count }}</span>
                        </span>
                    </td>
                    <td>
                        {{ $permission->label }}
                    </td>
                    <td>
                        <a href="{{ route('task-manager.permissions.edit', ['permission' => $permission->id]) }}" class="btn btn-sm btn-primary">
                            <i class="fas fa-pencil-alt"></i>
                        </a>
                    </td>
                    <td>
                        <form action="{{ route('task-manager.permissions.destroy', ['permission' => $permission->id]) }}" method="post">
                        @csrf
                        @method('DELETE')
                        <button type="submit" class="btn btn-sm btn-danger delete-btn" deleting-item="permission">
                            <i class="fas fa-trash"></i>
                        </button>
                        </form>
                    </td>
                </tr>
            @endforeach
        @endcomponent
    @endcomponent
    <div class="col-12 p-0 float-right text-center mt-3 mb-4">
        {{ $permissions->links() }}
    </div>
@endsection

@push('scripts')
    @if (config('app.env') == 'local')
    <script src="{{ asset('js/confirmDelete.js') }}"></script> 
    @else
    <script src="{{ asset(mix('js/confirmDelete.js')) }}"></script>
    @endif
@endpush