routes/web.php
<?php

use App\Broadcasting\TelegramChannel;
use App\Demand;
use App\Events\DemandFinished;
use App\Events\WorkspaceCreated;
use App\Notifications\DemandFinishedNotification;
use App\Notifications\WorkspaceNotification;
use App\User;
use App\Workspace;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::view('/', 'index');

Route::group(['prefix' => 'task-manager', 'as' => 'task-manager.', 'middleware' => ['auth']], function () {
    Route::view('/', 'theme.dashboard');
    Route::resource('users', 'UserController');
    Route::resource('roles', 'RoleController');
    Route::resource('permissions', 'PermissionController');
    Route::resource('priorities', 'PriorityController');
    Route::resource('workspaces',  'WorkspaceController');
    Route::resource('workspaces/{workspace}/demands', 'DemandController');
    Route::resource('tasks', 'TaskController')->only('index', 'show');
    Route::get('demands', 'DemandController@mixed')->name('demands.mixed');
    // Route::get('workspaces/{workspace}/tasks/{}', 'TaskController@index');
});

Auth::routes(['register' => false]);


// $user = auth()->user() ?: User::find(2);
// return $user->actions()->with('subject')->limit(5)->get();

// Route::get('/home', 'HomeController@index')->name('home');
// Route::post('/', function(Request $request) {
//     $dt = $request->due_to ? (new Carbon(((int) $request->due_to)))->timezone('Asia/Tehran')->seconds(0) : now();
//     return $dt->format('Y-m-d H:i:s');
// });

// Route::get('/chart', function() {
//     $user = User::first();
//     $dt_from = Carbon::createFromFormat('Y-m-d', '2020-12-21')->setTime(0,0);
//     $dt_to = Carbon::createFromFormat('Y-m-d', '2021-01-20')->setTime(0,0);
//     $craeted_tasks = $user->tasks()
//         ->where('created_at', '<', $dt_to)
//         ->where('created_at', '>=', $dt_from)
//         ->groupBy('date')
//         ->orderBy('date', 'asc')
//         ->get([
//             \DB::raw("COUNT(*) tasks, DATE_FORMAT(created_at, '%Y-%m-%e') date")
//         ]);
//     $finished_tasks = $user->tasks()
//     ->where('finished_at', '<', $dt_to)
//     ->where('finished_at', '>=', $dt_from)
//     ->whereNotNull('finished_at')
//     ->groupBy('date')
//     ->orderBy('date', 'asc')
//     ->get([
//         \DB::raw("COUNT(*) tasks, DATE_FORMAT(finished_at, '%Y-%m-%e') date")
//     ]);
//     $total_count = 0;
//     $finished_count = 0;
//     $target_task_days = collect([]);
//     foreach ($craeted_tasks as $task_day) {
//         $total_count += $task_day->tasks;
//         $task_day->total = $total_count;
//         foreach ($finished_tasks as $finished) {
//             if ($finished->date->diffInSeconds($task_day->date) == 0) {
//                 $finished_count += $finished->tasks;
//                 break;
//             }
//         }
//         $task_day->finished = $finished_count;
//         $task_day->percentage = round($finished_count / $total_count, 2) * 100;
//         $target_task_days->push($task_day);
//     }
//     $task_days = $target_task_days;
//     return view('chart', compact('task_days'));
// });

resources/views/theme/tools/menu.blade.php
<nav>
    <ul class="horizental-menu col-12">
        <li>
            <a href="{{ route('task-manager.') }}">داشبورد <i class="fas fa-tachometer-alt"></i></a>
        </li>
        <li>
            <a href="{{ route('task-manager.workspaces.index') }}">پروژه ها <i class="fas fa-project-diagram"></i></a>
        </li>
        <li>
            <a href="{{ route('task-manager.tasks.index') }}">مسئولیت ها <i class="fas fa-briefcase"></i></a>
        </li>
        <li>
            <a href="{{ route('task-manager.demands.mixed', ['tab' => 'asked_demands']) }}">درخواست ها <i class="fas fa-arrow-down"></i><i class="fas fa-list"></i></a>
        </li>
        <li>
            <a href="{{ route('task-manager.demands.mixed', ['tab' => 'demand']) }}">نیازها <i class="fas fa-arrow-up"></i><i class="fas fa-list"></i></a>
        </li>
        @if (auth()->user()->hasPermission('can_manage_system'))
        <li class="has_sub">
            <p>
                <a href="#demands">
                    مدیریت سیستمی <i class="fas fa-desktop"></i>
                </a>
                <i class="opener fa fa-angle-left"></i>
            </p>
            <ul>
                @can('viewAny', \App\User::class)
                <li class="sub">
                    <a href="{{ route('task-manager.users.index') }}">کاربران <i class="fas fa-users"></i></a>
                </li>
                @endcan
                @can('viewAny', \App\Role::class)
                <li class="sub">
                    <a href="{{ route('task-manager.roles.index') }}">سمت ها <i class="fas fa-user-tag"></i></a>
                </li>
                @endcan
                @can('viewAny', \App\Permission::class)
                <li class="sub">
                    <a href="{{ route('task-manager.permissions.index') }}">مجوز ها <i class="far fa-address-card"></i></a>
                </li>
                @endcan
                @if (auth()->user()->hasRole('developer'))
                <li class="sub">
                    <a href="{{ route('task-manager.priorities.index') }}">اولویت ها <i class="fas fa-list-ol"></i></a>
                </li>
                @endif
            </ul>
        </li>
        @endif
        <li>
            <a href="#" id="toggle-logout">خروج <i class="fas fa-power-off"></i></a>
        </li>
        <form class="d-none" id="logout-form" action="{{ route('logout') }}" method="POST">@csrf</form>
    </ul>
</nav>

resources/views/theme/tools/table-body.blade.php
<tbody>
    {!! $slot !!}
</tbody>

resources/views/theme/tools/table-head.blade.php
<thead class="thead-dark">
    <tr>
        {!! $slot !!}
    </tr>
</thead>

resources/views/theme/tools/table.blade.php
<table class="table table-striped table-bordered {{ isset($class) ? $class : '' }} float-right table-responsive w-100 d-block d-md-table">
    {!! $slot !!}
</table>

resources/views/theme/tools/title.blade.php
<div class="col-12 float-right mb-3">
    {{ $slot }}
    <h2 class="text-right">
        @if (isset($create))
        <a class="btn btn-info" href="{{ $create }}"><i class="fas fa-plus"></i></a>
        @endif
        {{ $title }}
    </h2>
</div>

resources/views/theme/tools/top-navbar.blade.php
<div class="col-12 navbar-top">
    <div>
        <div class="admin-info-container float-left">
            <a href="{{ route("task-manager.users.show", ["user" => auth()->user()->id]) }}" class="float-left mr-2">
                <img src="{{ asset(auth()->user()->avatar_pic ?: 'images/user-avatar.png') }}" alt="{{ auth()->user()->name }} profile photo">
            </a>
            <div>
                <p class="admin-email-link">{{ auth()->user()->email }}</p>
                <div class="btn-group drop-down-container">
                    <button type="button" class="btn btn-sm dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fas fa-user-tie"></i> {{ auth()->user()->name }}
                    </button>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="{{ route('task-manager.users.edit', auth()->user()->id) }}">تنظیمات <i class="fas fa-cog"></i></a>
                        <a id="logout-dropdown" href="#" class="dropdown-item">خروج <i class="fas fa-sign-out-alt"></i></a>
                    </div>
                </div>
            </div>
        </div>
        <div class="pt-3 pb-3">
            <button data-event="max" class="btn btn-outline-secondary scr-controller float-right d-none d-md-inline">
                <i class="fas fa-expand-arrows-alt fa-compress"></i>
            </button>
            <button id="refresh-btn" class="btn btn-light float-right ml-1 mr-1">
                <i class="fas fa-sync"></i>
            </button>
            <button class="btn btn-secondary float-right collapser-btn">
                <i class="fas fa-angle-double-left"></i>
            </button>
        </div>
    </div>
</div>